-- AlterTable
ALTER TABLE "expenses" ADD COLUMN "note" TEXT;

-- CreateEnum (idempotent)
DO $$
BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'activity_action') THEN
    CREATE TYPE "activity_action" AS ENUM ('MEMBER_ADDED', 'MEMBER_REMOVED', 'MANAGER_ASSIGNED', 'MEAL_ADDED', 'MEAL_UPDATED', 'MEAL_DELETED', 'EXPENSE_ADDED', 'EXPENSE_UPDATED', 'EXPENSE_DELETED', 'DEPOSIT_ADDED', 'DEPOSIT_UPDATED', 'MONTH_OPENED', 'MONTH_CLOSED', 'MEMBER_BALANCE_CREATED', 'DEFAULT_MEALS_UPDATED', 'BAZAAR_SUBMITTED', 'BAZAAR_UPDATED', 'BAZAAR_APPROVED', 'BAZAAR_REJECTED');
  ELSE
    ALTER TYPE "activity_action" ADD VALUE IF NOT EXISTS 'EXPENSE_DELETED';
  END IF;
END $$;
